Update ctitv.yml

diff --git a/.github/workflows/ctitv.yml b/.github/workflows/ctitv.yml
--- a/.github/workflows/ctitv.yml
+++ b/.github/workflows/ctitv.yml
@@ -22,6 +22,10 @@ jobs:
         run: |
           python -m pip install yt-dlp
 
+      - name: Save cookies file
+        run: |
+          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
+
       - name: Run script to update M3U
         run: |
           python ctitv.py
@@ -30,6 +34,10 @@ jobs:
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-          git add output/ctitv.m3u
-          git commit -m "Update IPTV stream URL" || echo "No changes to commit"
-          git push origin main || echo "No changes to push"
+          if [ -f "output/ctitv.m3u" ]; then
+            git add output/ctitv.m3u
+            git commit -m "Update IPTV stream URL" || echo "No changes to commit"
+            git push origin main || echo "No changes to push"
+          else
+            echo "M3U file not found, skipping commit."
+          fi
